### ISSUE TITLE
管理者権限、管理画面について色々

### ISSUE THREAD

**Issue by kitaindia** [masaki925/localis#1]
管理系のgemを色々入れました。
gem rorify
https://github.com/EppO/rolify
特定のuserに特定の権限を付与させるgem
  user = User.find(1)
  user.add_role :admin
とやると、1はadmin（管理者）、みたいな。

gem rails_admin
https://github.com/sferik/rails_admin
管理者ページで直接dbをいじれるもの。ここで、リクエストのoptionをtrueにしたりする。

リクエスト者のdb（option_qaとかの追加購入）は自分たち３人しかいじれないようにして、
リクエストの一覧は特定のユーザーのみ（プランを作成してくれる人、含む、自分たち）しかみられないようにするのはどうだろうか？

**Comment by masaki925** [comment]
ありがとうー
とりあえず今のところはよいのではないかな。

将来的に、もしDB を直接いじる管理画面が必要になった場合は、そもそも別のドメイン(admin.the-localis.com とか) にして、Web サーバ側で認証とかかけたいね。
ライブラリの脆弱性があってほげほげーとかbug でほげほげーとか なるとイヤなので。

まぁoption 系は機能として実装するはずなので、管理画面が必要になるとしても別の用途になる気もするけど。

**Comment by kitaindia** [comment]
返事おそくなりました、了解です。
rails_adminはつかわないようにしますー
